### ISSUE TITLE
Layout projection breaks after scrolling

### ISSUE THREAD

**Issue by rijk** [framer/motion#1214]
**CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-scroll-jump-issue-y97qn

**Steps to reproduce**

1. Click Menu button
2. Scroll colored area horizontally (make window smaller if there is no scroll)
3. Click one of the blue squares
3. Note white project container div shifting in the background while the modal is opening
4. Close modal
5. Note layout animation borked (lead/follow no longer synced)
6. Click Menu button 
7. Note project position is 'fixed' again by framer-motion when the tree is rerendered

**Expected behavior**

Scrolling should not affect layout transition functionality. When the transition starts it should calculate the correct coordinates taking the scroll position into account. Also, the parent div has no reason to shift horizontally as it does not even rerender?

**Video or screenshots**

https://user-images.githubusercontent.com/159500/125266186-dbfc0380-e305-11eb-9059-1d2dd8446e13.mov

**Comment by mattgperry** [comment]
This should be fixed with the perfect-projection branch but let’s keep this open so we can track it

**Comment by rijk** [comment]
[Not fixed](https://codesandbox.io/s/framer-motion-scroll-jump-issue-on-v500-pm75q?file=/src/Step.tsx) on `5.0.0-beta.22`:


https://user-images.githubusercontent.com/159500/131320089-411da375-8746-43ee-8f68-1fe134feb01f.mov

Here you can see initially the scrolling doesn't pose a problem, it starts when the sidebar is expanded:


https://user-images.githubusercontent.com/159500/131320284-75466404-3adc-43f4-b829-9195dab0878d.mov

Maybe it's because framer-motion assumes the scroll is directly relative to the viewport?

**Comment by rijk** [comment]
Fixed in 5.0.0-beta.28. Great work!

**Comment by rijk** [comment]
@mattgperry This is broken again in the latest version: https://codesandbox.io/s/framer-motion-scroll-jump-issue-2x0y4

https://user-images.githubusercontent.com/159500/134505447-a9649d7f-ce87-45b0-9348-fa68f96ff9a7.mov

**Comment by rijk** [comment]
More specifically this was broken between beta.35 and beta.36.

**Comment by mattgperry** [comment]
Scrollable elements need to be tagged with the `shouldMeasureScroll` prop (changing to `layoutScroll` in beta 45).

```jsx
<div className="projects">
// Becomes
<motion.div className="projects" shouldMeasureScroll>
```
