### ISSUE TITLE
[BUG] AnimatePresence doesn't update with the latest state if the state changes fast.

### ISSUE THREAD

**Issue by kyung-lee-official** [framer/motion#2023]
**Describe the bug**

`AnimatePresence` doesn't update with the latest state if the state changes fast.

**Provide a CodeSandbox reproduction of the bug**

```tsx
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";

const ComponentWrapper = (props: any) => {
	const { status } = props;
	return (
		<motion.div
			initial={{ opacity: 1 }}
			animate={{ opacity: 1 }}
			exit={{ opacity: 0 }}
		>
			<h1>{status}</h1>
		</motion.div>
	);
};

function ApBug() {
	const [status, setStatus] = useState<number>(1);
	return (
		<div>
			<AnimatePresence mode="wait">
				<ComponentWrapper key={status} status={status} />
			</AnimatePresence>
			<h1>status: {status}</h1>
			<button
				onClick={() => {
					setStatus(status + 1);
				}}
			>
				+1
			</button>
		</div>
	);
}

export default ApBug;
```

[CodeSandbox](https://codesandbox.io/p/sandbox/vite-animate-presence-zd5h44?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A37%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A37%7D%5D)

**Steps to reproduce**

If the `+1` button was clicked slowly, the animation will update with the state. While if the button was clicked swiftly, the animation stops updating with the state.

**Expected behavior**

The animation should update with the state.

**Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

https://user-images.githubusercontent.com/89364151/225664502-ac68c6cb-1979-418d-bde1-3710385d8049.mp4

**Environment details**

OS: 
Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎10/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0

Browser:
Chrome 
Version 111.0.5563.65 (Official Build) (64-bit)

npm package versions:

```json
{
  "name": "animation-sandbox",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "framer-motion": "^10.4.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.9.0",
    "styled-components": "^5.3.9"
  },
  "devDependencies": {
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@types/styled-components": "^5.1.26",
    "@vitejs/plugin-react": "^3.1.0",
    "typescript": "^4.9.5",
    "vite": "^4.2.0"
  }
}
```

**Comment by ndimatteo** [comment]
I'm getting the same issue on the latest version of framer motion `10.6.1`

https://user-images.githubusercontent.com/737188/226393677-6ce419be-1307-4db6-8e94-f0ba338e6b75.mov

You can see the _actual_ current index and caption below the framer animation. The moment I click faster than the animation takes, framer gets out of sync, despite a unique key being applied per the docs.

**Comment by EvHaus** [comment]
This is also happening for me as well after upgrading from 10.3.4 to 10.4.0. Looks like it was introduced as a regression in 10.4.0. It's especially easy to reproduce in unit tests where click events happen very quickly.

**Comment by ndimatteo** [comment]
I'm actually seeing this in a site running on `9.1.7` as well, so I'm not sure if this is a regression in v10 or just a long-standing bug?

There's no reason that if the key is _unique_ that nodes shouldn't be getting removed/added properly, regardless of how fast changes are happening. If that's not the case, that should be made clear in the docs 😬

**Comment by albinekman91** [comment]
I'm having the same issue switching between two components based on a state update: [reproduction](https://codesandbox.io/p/sandbox/vite-animate-presence-forked-4gmqjv?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A15%7D%5D)

**Comment by benjaminwaterlot** [comment]
I've got the exact same issue and found the regression version:

→ Works fine on `9.0.2`
→ Breaks on `9.0.3`

**Comment by michaeljblum** [comment]
I'm experiencing the same issue on `^10.9.1`. 

Would rather not roll back to v9 because clipPath anims only work in more recent versions for me. 

Anyone got a clue what broke? Like others said above it doesn't make much sense if key is reliably changing.

Anyway thanks for the sanity, confirmation. Not having any AnimatePresence problems on 9.0.2.

**Comment by varbrad** [comment]
Also experiencing the same issue on one of our projects where a modal stack state occasionally changes quite frequently and causes `AnimatePresence` to get out-of-sync and make our UI get all glitchy/frozen.

We're actually on version 6.5.1 (Stuck on React 17 😬) but I did a force-update to the latest version (10.12.4 at the time of writing) and the behaviour was the same.

**Comment by ndimatteo** [comment]
@mattgperry I think this is related to some tests in a PR you recently merged (#2119)...

I'm still seeing this issue persist even on the latest release (`10.12.11`).

Rapid changes cause items to not enter/exit properly on subsequent changes.

This is causing a real fuss in production, especially when you start doing scroll-related animations:

1. Previously removed `motion` components are not returning after rapid exits from `AnimatePresence`
2. Rapid `key` changes cause the current motion component to "stick" for subsequent changes, and then disappear for others

It's difficult to pinpoint what framer-motion is doing behind the scenes, but I can 100% confirm that the `key` is unique and properly updated regardless of how fast the change happens, but it seems that framer motion can't keep up or resync itself once the dust has settled.

**Comment by ndimatteo** [comment]
It does seem to be exclusively a problem with `mode="wait"` if that helps! 🤘

**Comment by ndimatteo** [comment]
Also for those still experiencing this, here's a quick workaround that seems to work well:

```js
<AnimatePresence mode="popLayout" initial={false}>
  // your unique motion component
</AnimatePresence>
```

And then add a `delay` to your `animate` transition that is **>=** to your `exit` transition.

Rapid changes do not experience the same degradation described in this thread 😎

**Comment by dpacmittal** [comment]
Downgrading to 9.0.2 fixed the issue for me. Thanks @benjaminwaterlot

**Comment by paavohuhtala** [comment]
I can confirm this still happens in the latest version. We have an animated modal dialog based on `<AnimatePresence>` which gets stuck if the user closes it too soon after opening. Rolling back to 9.0.2 fixes the issue.

**Comment by randex** [comment]
Same issue on the latest version (10.12.16). 

```
<AnimatePresence initial={false}>
    <div key={uuid}>
        ...
    </div>
<AnimatePresence>
```

Switching the uuid triggers the animation of that `div`, and if switching it fast enough, it breaks and doesn't get removed, so I see 2 divs stacked on each other: current one and its previous state that bugged out. Rolling back to 9.0.2 fixes the issue for me too.

**Comment by squidfunk** [comment]
Same problem here. Last version working for me is `10.5.0`. `10.6.0` breaks.

**Comment by karelhojda** [comment]
`10.12.17` stil getting stucked

**Comment by owjs3901** [comment]
10.12.22 still have bug.

**Comment by pofixifop** [comment]
10.13.0 still has the issue

**Comment by owjs3901** [comment]
This is a very important issue.

However, I have no idea what efforts Framer is making to fix this bug.
I am not even sure if they are aware of this bug.

I would like to know the roadmap or plan to fix this bug.

**Comment by pofixifop** [comment]
this bug is driving me crazy and comes up randomly in a not-always-reproducible fashion in production code where timing is a factor of client browser, backend job duration, react component states updating...

My current solution is to just comment out all exit props from variants and motion elements, which is obviously not ideal and ruins 50% of the reason we use framer-motion in the first place. It's making me seriously consider migrating away from this library completely, as animating a component while exiting and letting an entering component (often times the final value of some task that you want to display to the user) take its place is a huge deal, and can not break in a random fashion in production code! :(

**Comment by owjs3901** [comment]
@pofixifop If the migration target is decided, please share it.

We would also like to consider our organization.

**Comment by GianlucaGuarini** [comment]
@pofixifop @owjs3901 probably you can try to fix it with a PR instead of migrating your whole project to another library.

Framer motion is an open source project and the maintainer relies on the help of the community to fix such problems. Please consider contributing to the project ✌️

**Comment by hatsumatsu** [comment]
Okay, let's try help fix this.

Here is a minimal reproduction showing the issue:
https://codesandbox.io/s/framer-motion-animatepresence-bug-w4ycgz?file=/src/App.js

Trying out different version of `framer-motion` , I can not confirm [the 10.5.0 vs 10.6.0 theory](https://github.com/framer/motion/issues/2023#issuecomment-1596182075). 
However @benjaminwaterlot 's [9.0.2 vs 9.0.3-alpha.0 theory](https://github.com/framer/motion/issues/2023#issuecomment-1500694754) seems to be correct.

There seems to be a refactor of the ExitAnimation component between these versions:
https://github.com/framer/motion/compare/v9.0.2...v9.0.3-alpha.0

Anyone able to dig deep into this? 😇

**Comment by GianlucaGuarini** [comment]
The problem might be in [this method]( https://github.com/framer/motion/blob/main/packages/framer-motion/src/motion/features/animation/exit.ts#L8-L27).

Probably one of these early returns should be patched. I am at moment not able to work on it but hope that it might help anyone debugging the issue.

**Comment by pofixifop** [comment]
thanks for the attention guys 🥰

@hatsumatsu  the minimal repro sandbox is great - very concise and clearly showcases the issue

@mattgperry  let's do this!! 💪

**Comment by owjs3901** [comment]
I was ready to workspace to fix issue.

The `childrenToRender`  in `AnimatePresence.tsx/index.tsx` is an array, that contains the rendered elements.
Generally length of variable maintain 1, And In transition It will be 2.
But if the motion is done too fast, length will be over 1 at the moment of stopping.

I will Investigate why don't reduce this length.

If there are any additional achievements, I will comment.

![image](https://github.com/framer/motion/assets/12480623/252adaed-b9b4-42e7-aebe-f0511182f5fb)

**Comment by GianlucaGuarini** [comment]
My [patch](https://github.com/framer/motion/pull/2257) should fix this bug. Your feedback is welcome

**Comment by pofixifop** [comment]
> https://codesandbox.io/s/framer-motion-animatepresence-bug-w4ycgz?file=/src/App.js

Hey @GianlucaGuarini thanks for the efforts on this.

I patched my local, and unfortunately it did not fix the issue (the new onExitComplete code actually never ran, so the problem probably isn't that isPresent or prevIsPresent weren't true, and the issue lies somewhere else)

I also copy pasted the minimal reproduction sandbox code into my code, and clicking the "Update state" button quickly and repeatedly still easily reproduces the issue :)

**Comment by GianlucaGuarini** [comment]
@pofixifop thank you for your feedback. I was able to replicate the issue and fix it in my PR. Did you check also [this example](https://github.com/GianlucaGuarini/motion/commit/e34fc2233f93ecb8213638f7242bdca398b529e5#diff-adcb88ab2cc81b6ade4962be4e8ee2e59f87b1d633b256dd9f0aadf0d79c2786) Could you please let me know how to update it to replicate your issue? Thanks

**Comment by pofixifop** [comment]
> @pofixifop thank you for your feedback. I was able to replicate the issue and fix it in my PR. Did you check also [this example](https://github.com/GianlucaGuarini/motion/commit/e34fc2233f93ecb8213638f7242bdca398b529e5#diff-adcb88ab2cc81b6ade4962be4e8ee2e59f87b1d633b256dd9f0aadf0d79c2786) Could you please let me know how to update it to replicate your issue? Thanks

Hey @GianlucaGuarini Yep I saw your example, and it's great that it fixes the test example that you were ablw to make fail without your PR. I'm not exactly sure how to write a test that still fails it, or how to make a test that causes exactly the same behavior as a human clicking the button rapidly. Maybe the 50ms setTimeout delay is still too long? Or maybe there's a difference in how react/javascript process the ui interactions and animations that are different when rerendering after a setTimeout. I know a lot of the new code revolving around the exit animations use queueMicrotask, which would run at a higher priority than the setTimeout function. I know timing has a lot to do with this bug expressing itself, and that even printing a console.log to debug the issue can make the issue stop showing. It's a bit above my understanding of how this library works. But I would at least try to run the minimum reproducible code in the sandbox above in any attempted fix to see if the problem is truly solved before trying to create a testable example.

**Comment by hatsumatsu** [comment]
@GianlucaGuarini Your PR looks promising, would love to help test this! Is there build version from your branch to use in a codesandbox?

**Comment by pofixifop** [comment]
> could you please post a simple version of your failing example? So far my patch should cover all the issues reported in this thread

if you download the code at this sandbox

https://codesandbox.io/s/framer-motion-animatepresence-bug-w4ycgz?file=/src/App.js

and patch it with your patch, you can still reproduce the issue with just a single double-click of the button

**Comment by GianlucaGuarini** [comment]
@pofixifop are you sure that you are testing the right thing? 
That's the codebox result with my patch:

https://github.com/framer/motion/assets/879612/247a3d56-fb35-415a-acb3-c02bb2f43f74

**Comment by matthiaaas** [comment]
hey @GianlucaGuarini, can you try [this](https://codesandbox.io/s/framer-motion-animatepresence-buggy-rl8pd2?file=/src/App.tsx) codesandbox? It should show the bug clearer.

https://codesandbox.io/s/framer-motion-animatepresence-buggy-rl8pd2?file=/src/App.tsx

**Comment by pofixifop** [comment]
> @pofixifop are you sure that you are testing the right thing? That's the codebox result with my patch:


I thought I was, but maybe I didn't apply the patch correctly to my local branch? I thought I did as some other debug code I added was being called.
I must apologize - I tried out your sandbox, and also tried copying the framer-motion.js file from there into Matthias' code sandbox at https://codesandbox.io/s/framer-motion-animatepresence-buggy-rl8pd2?file=/src/App.tsx
They both saw the issue being resolved!!!

@GianlucaGuarini I am so grateful for your help and work fixing this bug, and I'm sure many others will also be stoked that this issue (and a ton of duplicate issues related to it) can finally be put to rest. ☺️

**Comment by federicocappellotto97** [comment]
+ 1
Same problem, animatePresence got out of sync when i update my state before the duration of transition is complete

**Comment by hatsumatsu** [comment]
@GianlucaGuarini Thanks so much, this fixes the issue in my tests. 
@mattgperry Any chance we could get this PR merged soon, would be fantastic to be able to use AnimatePresence in `framer-motion-3d` again.

**Comment by StLyn4** [comment]
Personally, the fix does not work for me in the production assembly (or when strict mode is turned off)

**Comment by donnellyjoe** [comment]
My temporary solve is to wrap each conditionally rendered item in its own AnimatePresence 🙃

**Comment by AlexMcClay** [comment]
I had to downgrade to 10.5.0 and that worked for the most part for me, I dont have any more issues with motion elements overlapping when having

  <AnimatePresence mode="popLayout">
  
  But There are still some cases where onExitComplete doesn't seem to be firing, even though I dont notice any layout differences.
  
 Hope this gets fixed soon.

**Comment by GianlucaGuarini** [comment]
Mi latest fixes the issue for React.Strict and non Strict mode. I have updated the [demo](https://codesandbox.io/s/framer-motion-animatepresence-bug-forked-c8pj74) to let you test it. 🎉

**Comment by GianlucaGuarini** [comment]
The exit transition lifecycle seem to be still problematic though. I will have a look at it as well.

**Comment by GianlucaGuarini** [comment]
My latest patch have finally fixed issue. [Here you can test it](https://codesandbox.io/s/framer-motion-animatepresence-bug-forked-c8pj74?file=/src/framer-motion.js)

**Comment by perrmadiafrrian** [comment]
Any update on this?

**Comment by federicocappellotto97** [comment]
> Any update on this?

+1

**Comment by hatsumatsu** [comment]
Curious if this doesn't affect paying framer users as well. Seems to affect such an important core functionality.

**Comment by jason-dark** [comment]
Also noticed this bug. Using framer 10.16.4.

**Comment by michaeljblum** [comment]
Is there a concrete reason this issue has gone unresolved for so long? Phrased differently, is there a compelling reason not to expect a fix for this issue? (Intended behavior, unintended but necessary outcome of more important logic that cannot be changed without causing more global issues, phasing out of FM maintenance to work on paid Framer products, etc...)

FM hits the absolute sweet spot of intuitive API and powerful/performant anims. But this is increasingly feeling like a deal breaker - if same-page enter/exit transitions are employed with the 'wait' mode applied anyway. I understand this is open source and with this comes no expectations of fixes, speedy or otherwise. Writing mainly because I'd just really prefer sticking with FM as my main React anim library.

**Comment by diegohaz** [comment]
Just had this issue. Latest version that works for me is `v10.3.4`.

It breaks on `v10.4.0`.

The [changelog](https://github.com/framer/motion/blob/main/CHANGELOG.md#1040-2023-03-16) doesn't seem to mention anything related to that:

> ## [[10.4.0] 2023-03-16](https://github.com/framer/motion/blob/main/CHANGELOG.md#1040-2023-03-16)
> ### [Added](https://github.com/framer/motion/blob/main/CHANGELOG.md#added-13)
> - animate() now supports DOM elements and DOM selectors.

**Comment by gerardmarquinarubio** [comment]
Still having this issue on 10.16.4. Any workarounds?

**Comment by devweissmikhail** [comment]
> Still having this issue on 10.16.4. Any workarounds?

Upgrading to later version 10.5.0 or 9.0.2 solves this problem
(I'm using mode="wait")

**Comment by AtoLrn** [comment]
I am having the same behavior with Remix and the Outlet component, when I stay on the same page but changes the key everythings works fine. But if I change a page (implies the Outlet component to render a new child) the exit animations will skip. I noticed that on version 10.16.4 something blocks the re-render and let the key unchanged (works fine in 9.0.2 but with the exit skip).

**Comment by codingwithdidem** [comment]
10.12.22 have this problem too

**Comment by sikandarchishty** [comment]
I had the same issue with `mode="wait"`, where I was changing images in a slider where I was quickly changing images with button click.

 Use `mode="popLayout"` on `AnimatePresence`, works for me.

**Comment by drscottlobo** [comment]
I'm having the same issue 10.16.4

**Comment by AndonMitev** [comment]
I can spot some issue as well with `mode="popLayout"`

Having this example:
```
const contentVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1 },
};


  <AnimatePresence mode="popLayout">
          {tab === TABS.SEND ? (
            <motion.div
              className="w-full"
              key="send"
              initial="hidden"
              animate="visible"
              exit="hidden"
              variants={contentVariants}
              transition={{ duration: 0.5 }}
            >
              <Send />
            </motion.div>
          ) : (
            <motion.div
              className="w-full"
              key="receive"
              initial="hidden"
              animate="visible"
              exit="hidden"
              variants={contentVariants}
              transition={{ duration: 0.5 }}
            >
              <Receive />
            </motion.div>
          )}
        </AnimatePresence>
```

when switching between tabs kinda fast, content might get mixed and lets say i'm on Send tab, i can see Send and Receive content under the same tab any ideas

**Comment by hatsumatsu** [comment]
@mattgperry Thanks so much for merging the PR! In 10.16.5 the issue is solved in my test case:

https://codesandbox.io/s/framer-motion-animatepresence-bug-w4ycgz

**Comment by didemkkaslan** [comment]
thanks @mattgperry  10.16.5  works for me too 🎉

**Comment by gorchov** [comment]
10.16.5 fixed it.

**Comment by rjpaul2** [comment]
`10.16.5` fixed for me too. Thanks @mattgperry

**Comment by Pdhenrique** [comment]
Estou tendo este problema utilizando mode="wait". No meu caso é utilizado em um componente de Accordion. Testei alguns casos passados anteriormente mas nenhum com sucesso, e removendo o mode="wait" os accordions quando clicados rapidamente passam a não atualizar corretamente e não fecham mais. 

Versão do framer usada: 10.16.5

```
 const variants = {
  open: { height: 'auto' },
  closed: { height: 0 }
}

export const Accordion: FC<AccordionProps> = memo(
  ({
    'data-testid': datatestId = 'accordion',
    align,
    children,
    disabled,
    divider,
    expanded = false,
    header,
    onExpand,
    id,
    ...props
  }) => {
    const accordionContentRef = useRef<HTMLDivElement>(null)
    const MotionBox = motion(Box)
    const headerElement = () => {
      if (typeof header === 'string') {
        return (
          <AccordionHeader
            align={align}
            data-testid={`${datatestId}-header`}
            disabled={disabled}
            divider={divider}
            expanded={expanded}
            onExpand={onExpand}
            id={id}
          >
            <Text
              color={disabled ? 'neutralMedium60' : 'neutralDark80'}
              data-testid={`${datatestId}-header--content-children-text`}
              fontSize="xs"
              fontWeight="semibold"
              letterSpacing="0.1px"
              lineHeight="24px"
              overflow="hidden"
              textOverflow="ellipsis"
              whiteSpace="nowrap"
            >
              {header}
            </Text>
          </AccordionHeader>
        )
      }
      return header
    }

    return (
      <StyledAccordion
        data-testid={datatestId}
        display="flex"
        flexDirection="column"
        {...props}
      >
        {headerElement()}
        <AnimatePresence>
          {expanded && (
            <MotionBox
              animate={expanded ? 'open' : 'closed'}
              exit="closed"
              initial="closed"
              style={{ overflow: 'hidden' }}
              variants={variants}
              transition={{
                when: 'beforeChildren',
                height: {
                  type: 'tween',
                  duration: 0.3,
                  ease: 'easeOut'
                }
              }}
            >
              <Box
                data-testid={`${datatestId}--content`}
                ref={accordionContentRef}
              >
                {children}
              </Box>
            </MotionBox>
          )}
        </AnimatePresence>
        {divider && (
          <Divider
            borderColor="neutralMedium40"
            data-testid={`${datatestId}--divider`}
            mt={expanded ? 'quark' : 0}
            opacity={expanded ? 1 : 0}
          />
        )}
      </StyledAccordion>
    )
  }
)
```

**Comment by Ou7law007** [comment]
I don't think this is fixed on 10.16.5.

If a page change with `router` is involved, and the page is changed very quickly back and forth, the page and url desync which causes a very weird bug. The entire page bugs out making it render the wrong component `router element` for a url route.

I don't know if this is a different issue though. I've had it for a while and `10.16.5` did not fix it.

I'm unable to make a sandbox example at this moment, maybe someone else who's having this issue could confirm.

**Comment by liho00** [comment]
> Same problem here. Last version working for me is `10.5.0`. `10.6.0` breaks.

10.16.5 still not working, 10.12.2 is working

**Comment by michaeljblum** [comment]
Fixed for me!

Literally just ran into this issue for like the fifth time in two years. Sick of workarounds, was considering going back to RTG for enter/exit. 

Checked this thread on a whim and woah! Great work, no more breaking for me on `10.16.9`

**Comment by oliviercperrier** [comment]
Still getting this with: 11.0.24

**Comment by NatanielRegula** [comment]
For me the issues still persist on: 11.2.11

Versions that seem to work: 9.0.2 and 10.12.2

I get the same bug that @randex mentioned, where if motion.div changes too quickly they might get stuck on the page and 2 or more will be displayed on the screen.

Another issue that exists on the above mentioned version but not on the older working versions is if the motion.div changes between next and previous item (in a carousel) quickly the enter animation is played twice. This only happens if we change from item index 2 to index 1 and back to index 2 not when changing sequentially index 1 index 2 index 3 and so on.

**Comment by LeonLiu2020** [comment]
Ran into the same problem on 11.2.12
When quickly switching states, results in incorrect conditional rendering. The elements stay rendered and the state can no longer be switched.

**Comment by hatsumatsu** [comment]
> Ran into the same problem on 11.2.12 When quickly switching states, results in incorrect conditional rendering. The elements stay rendered and the state can no longer be switched.

@LeonLiu2020 I tried to reproduce your issue with my old prototype and framer-motion `11.2.12` and everything seems to work as expected: https://codesandbox.io/p/sandbox/framer-motion-animatepresence-bug-w4ycgz

Can you share a minimal reproduction with us?

**Comment by LeonLiu2020** [comment]
> > Ran into the same problem on 11.2.12 When quickly switching states, results in incorrect conditional rendering. The elements stay rendered and the state can no longer be switched.
> 
> @LeonLiu2020 I tried to reproduce your issue with my old prototype and framer-motion `11.2.12` and everything seems to work as expected: https://codesandbox.io/p/sandbox/framer-motion-animatepresence-bug-w4ycgz
> 
> Can you share a minimal reproduction with us?

Here are two links. The code is the same except for the version of framer-motion.
11.2.12： https://codesandbox.io/p/devbox/framer-motion-11-2-12-s2rwgt
11.0.10：https://codesandbox.io/p/devbox/framer-motion-11-0-10-6f43vg

**Comment by LeonLiu2020** [comment]
@hatsumatsu
Here are two demonstration videos：
https://github.com/framer/motion/assets/13536658/b82518aa-28ec-414b-ba8d-b284806261b9
https://github.com/framer/motion/assets/13536658/11f36bee-3d98-4193-959d-36cf7cff4f86

**Comment by hatsumatsu** [comment]
> @hatsumatsu Here are two links. The code is the same except for the version of framer-motion. 11.2.12： https://codesandbox.io/p/devbox/framer-motion-11-2-12-s2rwgt 11.0.10：https://codesandbox.io/p/devbox/framer-motion-11-0-10-6f43vg

@LeonLiu2020 In your example the animated `<motion.div />` is not a direct child of `<AnimatePresence />` on contrast to the [docs](https://www.framer.com/motion/animate-presence/##exit-animations). When I wrap your tooltip component in another `<motion.div/>` it seems to work as expected:

````jsx
<AnimatePresence>
  {open && (
    <motion.div>
      <Tooltip.Content>
        <motion.div
          initial={{ y: 15, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ ease: "easeInOut", duration: 0.2 }}
          exit={{ y: 15, opacity: 0 }}
        >
          My tooltip
        </motion.div>
      </Tooltip.Content>
    </motion.div>
  )}
</AnimatePresence>;
````

**Comment by LeonLiu2020** [comment]
@hatsumatsu
Thank you very much, you are a patient and kind person.
 In the <Tooltip.Content> component, there is an asChild prop, which means that this component will render as a child node and will not present itself in the DOM. This usage was not a problem in previous versions of framer-motion, and all blogs and tutorials online combined radix-primitives and framer-motion in this way. However, with the updates to framer-motion and radix-primitives, it seems that we can no longer simply treat radix components with the asChild prop as direct child nodes.

```
<AnimatePresence>
      {open && (
                    <Tooltip.Content
                      asChild
                    >
                      <motion.div
                        initial={{ y: 15, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ ease: "easeInOut", duration: 0.2 }}
                        exit={{ y: 15, opacity: 0 }}/>
                    </Tooltip.Content>
                )}
</AnimatePresence>
```

**Comment by mekaseymour** [comment]
> I don't think this is fixed on 10.16.5.
> 
> 
> 
> If a page change with `router` is involved, and the page is changed very quickly back and forth, the page and url desync which causes a very weird bug. The entire page bugs out making it render the wrong component `router element` for a url route.
> 
> 
> 
> I don't know if this is a different issue though. I've had it for a while and `10.16.5` did not fix it.
> 
> 
> 
> I'm unable to make a sandbox example at this moment, maybe someone else who's having this issue could confirm.
> 
> 

I'm having this issue with react router too 😭 Did you ever figure out a workaround?

**Comment by Melvynx** [comment]
Same issue with `11.3.19`
