### ISSUE TITLE
[BUG] Slideshow Example not working correctly in in v1.6.18+

### ISSUE THREAD

**Issue by clintjansen** [framer/motion#419]
https://codesandbox.io/s/framer-motion-image-gallery-pqvx3?fontsize=14&module=%2Fsrc%2FExample.tsx

Select version 1.6.18 or higher and the animation will not be correct anymore.
The image is moving back & forth instead of the slides going one way.

**Comment by InventingWithMonster** [comment]
Thanks for letting me know! I think this was actually a bug before. I've updated the code and it looks correct to me now.

**Comment by clintjansen** [comment]
Heya, thanks for looking into this!

I still have the same issue, but it's because I am using the code differently.
I am using Class component & with redux controlling the pagination.

The weird issue is, when I add the drag='x/y' prop to the <motion> element it does work correctly using said method.
But without I get the visual bug again.

And I need my slider to be non-draggable
Do you have any idea what's the problem here?
Thanks!

**Comment by clintjansen** [comment]
Well, I managed to fix it by using the Redux hooks and keeping it functional component instead :)
