### ISSUE TITLE
[BUG] Motion elements does not follow parent component when dragged after react state update. 

### ISSUE THREAD

**Issue by micnil** [framer/motion#636]
**Describe the bug**
When dragging a `motion.ul` element i expect the children `motion.li` to also be dragged along. This works fine directly after mount, but as soon as we update the state of the component, the list elements becomes static.

I first suspected it was just something I'm missing in the new API, so I [wrote a question](https://stackoverflow.com/questions/62935368/child-components-are-not-dragged-with-parent-after-react-state-update-in-framer) on Stack Overflow. But after simplifying it further, and comparing with version 1.11.1, I now suspect this is a bug.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[https://codesandbox.io/s/framer-motion-reorder-animation-go6tb](https://codesandbox.io/s/framer-motion-reorder-animation-go6tb?file=/src/Example.tsx)

**Steps to reproduce**

1. Drag the yellow background => Colored boxes follows the drag motion
2. Click on "Shuffle"
3. Drag the yellow background => Colored boxes do not move.

**Expected behavior**
I expect the colored boxes to behave the same before and after the shuffle. This worked in version 1.11.1 (only code difference is using `positionTransition` instead of `layout` prop):
![drag-motion-1 11 1](https://user-images.githubusercontent.com/4202345/87713879-34f49280-c7ab-11ea-9ab6-262f3ca3c8d0.gif)

**Video or screenshots**
![drag-motion-2 0 1](https://user-images.githubusercontent.com/4202345/87714061-7e44e200-c7ab-11ea-91f7-8d2f087d7336.gif)

**Environment details**
Windows 10
Chrome Version 83.0.4103.116

**Comment by micnil** [comment]
Maybe a better example:

[https://codesandbox.io/s/framer-motion-reorder-animation-dhfw2](https://codesandbox.io/s/framer-motion-reorder-animation-dhfw2?file=/src/Example.tsx)

In this example the button simply sets some local state that is not used anywhere. In other words, all it does is trigger a rerender. Still the dragging stops working after clicking it.

**Comment by InventingWithMonster** [comment]
After a render layout projection has been enabled so elements are trying to project themselves to a specific place on the viewport.

At some point soonish I want to look into resolving these bounding boxes relatively to parents so I imagine this will fix that.

**Comment by micnil** [comment]
Seems like this was fixed in version 2.4.0, Thank you!

**Comment by alaister** [comment]
@micnil Would you mind reopening this issue? Although it seems to have fixed the case in your example, #663 still appears to be broken.

Thanks

**Comment by micnil** [comment]
Updated my codepen with a failing example here: 
[https://codesandbox.io/s/framer-motion-reorder-animation-forked-j4blh](https://codesandbox.io/s/framer-motion-reorder-animation-forked-j4blh?file=/src/Example.tsx)

It seems it is still broken if both the draggable parent and children have the `layout` prop set. In my original example only the children had the `layout` prop set. I assume this is what the problem is with #663

**Comment by rijk** [comment]
I think I have the same issue. This is a flex layout where the sidebar animation happens through `layout`:

![board-no-layout](https://user-images.githubusercontent.com/159500/97445718-ddc79780-192d-11eb-966e-a5b3d01ef2e6.gif)

And this is the exact same, only with a `layoutId` applied to the third blue square (to make a iOS home screen-style transition into a modal):

![boards-layout](https://user-images.githubusercontent.com/159500/97445911-10719000-192e-11eb-992c-68014a82a1ed.gif)

As is visible, it now performs an unwanted transform correction for the parent, making it jump to the end position. When I override the element with `transform: none !important`, it transitions nicely as in the above example.

**Comment by rijk** [comment]
Temporarily overriding with `transform: none !important` worked as a workaround during animations, but I'm now running into the dragging issue as well.
