### ISSUE TITLE
Background color not animating via className change

### ISSUE THREAD

**Issue by jca41** [framer/motion#842]
**2. Describe the bug**

I was inspecting this switch/toggle example where the position of the handle animates as well as the background color of the component.

This is done by switching classNames based on state (`.on` and `.off`)
This example no longer works with recent versions of this package (using 2.9.4).

I understand this might be an API change instead of a bug, but is there a way to achieve what's being showcased with newer versions of this package?

I'm using tailwindcss, so i was hoping to just add a `bg-green-400` when the toggle is on.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/0d68e?file=/package.json

**4. Steps to reproduce**

1. Open codesandbox link
2. Switch to a recent version of framer-motion
3. try the toggle

**5. Expected behavior**

Was expecting the toggle to animate position and color.

**Comment by jca41** [comment]
Update: 

i can fix the position animation by adding layout to the child motion.div.
Still haven't found a solution for the background color animation.

**Comment by KirdesMF** [comment]
you need to add a transition to your class if you want to animate via classname. I guess the layout prop let you animate only the layout position not the color or background color.

Here a codesandbox with both solution. 

https://codesandbox.io/s/framer-motion-automatic-animation-switch-demo-forked-dk1bj?file=/src/App.js

**Comment by jca41** [comment]
`  transition: background-color 0.5s ease;
`

This bit was the key, ended up doing the same with tailwind. Out of curiosity is there a reason why this doesn't work anymore? It's still working with version "2.0.0-beta.41" but not with the latest

**Comment by KirdesMF** [comment]
no idea sorry

**Comment by jordant97** [comment]
Is there any undocumented breaking changes that happen between v2.0.0-beta.41 and the latest version? AnimateSharedLayout is working fine in v2.0.0-beta.41 but not 3.1.1 (Background color and shape is not changing)

**Comment by mattgperry** [comment]
`animate` became `layout` and everything else has to be animated via `animate={}`. We're experimenting with things that get crossfaded between components, `backgroundColor` and `borderRadius` should be working correctly in latest.

**Comment by choco** [comment]
Sorry, I still don't understand if current behaviour is expected or it should allow animating also the background color and border radius without having to explicitly add the values inside the `animate` property

**Comment by mattgperry** [comment]
It is expected
